USE [master]
GO

/****** Object:  Database [RouletteDb]    Script Date: 2023/01/09 22:38:02 ******/
CREATE DATABASE [RouletteDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RouletteDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\RouletteDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RouletteDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\RouletteDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RouletteDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RouletteDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RouletteDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RouletteDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RouletteDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RouletteDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [RouletteDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RouletteDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RouletteDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RouletteDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RouletteDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RouletteDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RouletteDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RouletteDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RouletteDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RouletteDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RouletteDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RouletteDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RouletteDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RouletteDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RouletteDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RouletteDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RouletteDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RouletteDb] SET RECOVERY FULL 
GO

ALTER DATABASE [RouletteDb] SET  MULTI_USER 
GO

ALTER DATABASE [RouletteDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RouletteDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RouletteDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RouletteDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RouletteDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RouletteDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RouletteDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RouletteDb] SET  READ_WRITE 
GO


