USE[RouletteDb]
GO

/****** Object:  Table [dbo].[SpinHistory]    Script Date: 2023/01/09 22:07:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SpinHistory] (
    [Id][int] IDENTITY(1, 1) NOT NULL,
    [SpinValue] [int] NOT NULL,
CONSTRAINT[PK_SpinHistory] PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON[PRIMARY]
) ON[PRIMARY]
GO